### ISSUE TITLE
Unmatched DL4J version between client and server

### ISSUE THREAD

**Issue by thangnbn** [mccorby/PhotoLabellerServer#11]
I observed that when the client sends weight updates back to server, I get the following exception. I figured out that the client used DL4J 1.0.0-beta3, while the server used 0.8.0, and there is an enum that doesn't exist in the older version.

How do you resolve this exception? We cannot downgrade the client version since 0.8.0 doesn't support ARM (I think - I tried to downgrade and it seems so). We cannot upgrade the server to 1.0.0-beta3 as well, since there are many library methods that are used in `com.mccorby.photolabeller.ml.Main.kt` are depreciated in newer version.

```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant org.nd4j.linalg.api.buffer.DataBuffer.AllocationMode.LONG_SHAPE
```

**Comment by Steven0038** [comment]
Hi, bnnthang

Thanks for post this issue.
I tried this project last year, and run FederatedAverage stratagy successfuly,
but when I tried it again recently with new insallation, I have the same exception as yours.

I think it's might be the problem of some dependency library on maven have slighty changes, even they share the same version number.

I upgrade the server to 1.0.0-beta3, and it works well with client side
, but I modified the ``com.mccorby.photolabeller.ml.Main.kt `` and other class a lot to suit the newer version of dj4j.

You might could checkout this [brench](https://github.com/mccorby/PhotoLabellerServer/compare/master...Steven0038:feature/20220224_global_image_classifier) for more details about newer version.

**Comment by thangnbn** [comment]
Hi @Steven0038,

Thanks for your concern. I also did somewhat the same thing you did [in my fork](https://github.com/bnnthang/PhotoLabellerServer/tree/mismatched-dl4j-version-hotfix). Basically, we both "commented" out the `predict` method in `Main.kt` file of the ML module and made other needed justifications.

I guess probably someone need to redo this project if we want to completely upgrade to the newer version since there are a lot of deprecated methods.
